"""Parser tests — every example file and every documented format edge case."""
from __future__ import annotations

import textwrap
from pathlib import Path

import pytest

from app.notebook import from_ipynb, from_markdown, from_py

EXAMPLES = Path(__file__).resolve().parent.parent.parent / "examples"


# ---------- v1: legacy single-callout format ----------

def test_parse_v1_single_callout():
    src = textwrap.dedent("""\
        # %% kind=function color=mint title="Demo"
        # @explain: single callout body
        # @tags: t1, t2
        def f(x):
            return x + 1
    """).encode()
    nb = from_py("v1.py", src)
    assert len(nb.cells) == 1
    c = nb.cells[0]
    assert c.kind == "code"
    assert c.meta is not None
    assert c.meta.kind == "function"
    assert c.meta.color == "mint"
    assert c.meta.title == "Demo"
    assert c.meta.explain == "single callout body"
    assert c.meta.tags == ["t1", "t2"]
    assert c.meta.callouts == []
    assert "def f(x):" in c.source


def test_explain_lines_joined_with_space():
    src = b"# %% title=\"X\"\n# @explain: line one\n# @explain: line two\nx = 1\n"
    nb = from_py("x.py", src)
    assert nb.cells[0].meta.explain == "line one line two"


# ---------- markdown ----------

def test_markdown_cell_strips_leading_hash():
    src = b"# %% [markdown]\n# # Heading\n# Some text.\n#\n# More.\n"
    nb = from_py("m.py", src)
    assert len(nb.cells) == 1
    assert nb.cells[0].kind == "markdown"
    assert nb.cells[0].source == "# Heading\nSome text.\n\nMore."


# ---------- v2: multiple callouts ----------

def test_v2_multiple_callouts():
    src = textwrap.dedent("""\
        # %% kind=function color=mint title="Main"
        # @explain: primary body
        # @callout title="Aside" color=peach
        # @explain: second body
        # @callout
        # @title: Third
        # @color: lavender
        # @explain: third body
        def f(x):
            return x
    """).encode()
    nb = from_py("v2.py", src)
    m = nb.cells[0].meta
    assert m is not None
    assert m.title == "Main"
    assert m.color == "mint"
    assert m.explain == "primary body"
    assert len(m.callouts) == 2
    assert m.callouts[0].title == "Aside"
    assert m.callouts[0].color == "peach"
    assert m.callouts[0].explain == "second body"
    assert m.callouts[1].title == "Third"
    assert m.callouts[1].color == "lavender"
    assert m.callouts[1].explain == "third body"


def test_v2_image_directive_kept_as_string():
    img = "data:image/png;base64,AAAA"
    src = (
        f'# %% title="x"\n'
        f"# @image: {img}\n"
        f"# @explain: with image\n"
        f"y = 1\n"
    ).encode()
    nb = from_py("img.py", src)
    assert nb.cells[0].meta.image == img


# ---------- whitespace / odd formats ----------

def test_plain_file_no_markers_becomes_one_cell():
    src = b"print('hello')\n"
    nb = from_py("plain.py", src)
    assert len(nb.cells) == 1
    assert nb.cells[0].kind == "code"
    assert nb.cells[0].meta is None


def test_preamble_only_is_dropped():
    """Files starting with `# doodlecode format-version: …` shouldn't
    produce a leading code cell from the comment header."""
    src = (
        b"# doodlecode format-version: 2\n"
        b"# Generated by DoodleCode Studio\n\n"
        b"# %% [markdown]\n# title\n\n"
        b"# %% title=\"X\"\n# @explain: body\nx = 1\n"
    )
    nb = from_py("preamble.py", src)
    assert len(nb.cells) == 2
    assert nb.cells[0].kind == "markdown"


def test_format_version_picked_up_from_preamble():
    src = b"# doodlecode format-version: 2\n# %% [markdown]\n# heading\n"
    nb = from_py("x.py", src)
    assert nb.format_version == 2


def test_real_code_before_first_marker_is_kept():
    src = b"x = 1\n# %% title=\"a\"\nprint(x)\n"
    nb = from_py("x.py", src)
    assert len(nb.cells) == 2
    assert "x = 1" in nb.cells[0].source


def test_invalid_python_still_splits():
    """Cell splitting is comment-based and must not touch the AST."""
    src = b"# %% [markdown]\n# hi\n\n# %% title=\"bad\"\ndef broken(:\n"
    nb = from_py("bad.py", src)
    assert len(nb.cells) == 2


# ---------- ipynb ----------

def test_ipynb_basic():
    raw = b"""{
      "cells": [
        {"cell_type": "markdown", "source": "# Heading\\n"},
        {"cell_type": "code", "source": ["print(1)\\n", "print(2)\\n"]}
      ]
    }"""
    nb = from_ipynb("x.ipynb", raw)
    assert len(nb.cells) == 2
    assert nb.cells[0].kind == "markdown"
    assert nb.cells[1].source == "print(1)\nprint(2)\n"


# ---------- markdown file ----------

def test_from_markdown_splits_python_blocks():
    src = b"intro\n\n```python\nx = 1\n```\n\nmiddle\n\n```python\ny = 2\n```\n"
    nb = from_markdown("m.md", src)
    kinds = [c.kind for c in nb.cells]
    assert "code" in kinds and "markdown" in kinds


# ---------- every shipped example ----------

@pytest.mark.parametrize("path", sorted(EXAMPLES.glob("*.py")))
def test_every_example_parses(path: Path):
    raw = path.read_bytes()
    nb = from_py(path.name, raw)
    assert nb.cells, f"{path.name} produced 0 cells"
    # At least one code or markdown cell should have meaningful content
    assert any(c.source.strip() for c in nb.cells), f"{path.name} all-empty cells"
